name: Odin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Install Odin
        run: |
          git clone https://github.com/odin-lang/Odin.git
          cd Odin
          make

      - name: Build Project
        run: |
          cd ${{ github.workspace }}
          ./Odin/odin build .